create table "public"."agregados_globales_pedido" (
    "id" bigint generated by default as identity not null,
    "id_pedido" bigint,
    "id_agregado" bigint
);

alter table "public"."agregados_globales_pedido" enable row level security;

alter table "public"."agregados_globales_pedido"
    add constraint "agregados_globales_pedido_pkey" primary key ("id");

alter table "public"."agregados_globales_pedido"
    add constraint "agregados_globales_pedido_id_agregado_fkey"
    foreign key (id_agregado) references public.agregados(id);

alter table "public"."agregados_globales_pedido"
    add constraint "agregados_globales_pedido_id_pedido_fkey"
    foreign key (id_pedido) references public.pedidos(id);

grant delete, insert, references, select, trigger, truncate, update
    on table "public"."agregados_globales_pedido" to "anon";
grant delete, insert, references, select, trigger, truncate, update
    on table "public"."agregados_globales_pedido" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update
    on table "public"."agregados_globales_pedido" to "service_role";