CREATE TABLE IF NOT EXISTS "public"."producto_componentes" (
    "id" bigint NOT NULL,
    "id_producto_combo" bigint NOT NULL,
    "id_producto_componente" bigint NOT NULL,
    "cantidad" integer NOT NULL DEFAULT 1
);

ALTER TABLE "public"."producto_componentes" OWNER TO "postgres";

ALTER TABLE "public"."producto_componentes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."producto_componentes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."producto_componentes"
    ADD CONSTRAINT "producto_componentes_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."producto_componentes"
    ADD CONSTRAINT "producto_componentes_combo_fkey" FOREIGN KEY ("id_producto_combo") REFERENCES "public"."productos"("id");

ALTER TABLE ONLY "public"."producto_componentes"
    ADD CONSTRAINT "producto_componentes_componente_fkey" FOREIGN KEY ("id_producto_componente") REFERENCES "public"."productos"("id");

ALTER TABLE ONLY "public"."producto_componentes"
    ADD CONSTRAINT "producto_componentes_combo_componente_unique" UNIQUE ("id_producto_combo", "id_producto_componente");

CREATE INDEX "idx_producto_componentes_combo" ON "public"."producto_componentes" USING "btree" ("id_producto_combo");

ALTER TABLE "public"."producto_componentes" ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE "public"."producto_componentes" TO "anon";
GRANT ALL ON TABLE "public"."producto_componentes" TO "authenticated";
GRANT ALL ON TABLE "public"."producto_componentes" TO "service_role";
GRANT ALL ON SEQUENCE "public"."producto_componentes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."producto_componentes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."producto_componentes_id_seq" TO "service_role";

ALTER TABLE "public"."prendas_pedido" RENAME COLUMN "pedido" TO "id_pedido";
ALTER TABLE "public"."prendas_pedido" RENAME COLUMN "producto" TO "id_producto";

ALTER TABLE "public"."prendas_pedido"
    ADD COLUMN "id_producto_pedido" bigint;

ALTER TABLE ONLY "public"."prendas_pedido"
    ADD CONSTRAINT "prendas_pedido_producto_pedido_fkey" FOREIGN KEY ("id_producto_pedido") REFERENCES "public"."productos_pedidos"("id");

CREATE INDEX "idx_prendas_pedido_producto_pedido" ON "public"."prendas_pedido" USING "btree" ("id_producto_pedido");