drop extension if exists "pg_net";


  create table "public"."agregados" (
    "id" bigint generated by default as identity not null,
    "agregado" text,
    "precio" real,
    "individual" boolean default true
      );


alter table "public"."agregados" enable row level security;


  create table "public"."alumnos_responsables" (
    "id" bigint generated by default as identity not null,
    "id_grupo" bigint,
    "nombre" text,
    "apellido" text,
    "telefono" text
      );


alter table "public"."alumnos_responsables" enable row level security;


  create table "public"."auditoria" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "usuario" bigint not null,
    "tabla" text not null,
    "accion" text not null,
    "dato_anterior" text,
    "dato_nuevo" text,
    "registro_id_modificado" bigint
      );


alter table "public"."auditoria" enable row level security;


  create table "public"."beneficios" (
    "id" bigint generated by default as identity not null,
    "beneficio" text
      );


alter table "public"."beneficios" enable row level security;


  create table "public"."colegios" (
    "id" bigint generated by default as identity not null,
    "nombre" text not null,
    "localidad" text not null,
    "provincia" text not null
      );


alter table "public"."colegios" enable row level security;


  create table "public"."contratos" (
    "id" bigint generated by default as identity not null,
    "grupo" bigint,
    "documento" bigint,
    "firmado" boolean,
    "fecha_generación" date,
    "fecha_firma" date
      );


alter table "public"."contratos" enable row level security;


  create table "public"."cuotas" (
    "id" bigint generated by default as identity not null,
    "id_pedido" bigint not null,
    "numero" integer,
    "fecha_vencimiento" date,
    "importe" double precision,
    "estado" text default '"Pendiente"'::text,
    "fecha_pago" date
      );


alter table "public"."cuotas" enable row level security;


  create table "public"."documentos" (
    "id" bigint generated by default as identity not null,
    "id_grupo" bigint not null,
    "tipo" text,
    "archivo_url" text,
    "created_at" timestamp without time zone default now()
      );


alter table "public"."documentos" enable row level security;


  create table "public"."grupos" (
    "id" bigint generated by default as identity not null,
    "id_colegio" bigint not null,
    "orientacion" text,
    "turno" text,
    "nivel" text,
    "promo" bigint,
    "cantidad_egresados" bigint,
    "created_at" timestamp without time zone default now()
      );


alter table "public"."grupos" enable row level security;


  create table "public"."movimientos" (
    "id" bigint generated by default as identity not null,
    "id_grupo" bigint not null,
    "importe" double precision,
    "fecha" timestamp without time zone default now()
      );


alter table "public"."movimientos" enable row level security;


  create table "public"."padres_responsables" (
    "id" bigint generated by default as identity not null,
    "nombre" text,
    "apellido" text,
    "dni" text,
    "telefono" text,
    "mail" text,
    "id_grupo" bigint
      );


alter table "public"."padres_responsables" enable row level security;


  create table "public"."pagos" (
    "id" bigint generated by default as identity not null,
    "id_pedido" bigint,
    "nro_transferencia" text,
    "tipo_pago" text,
    "monto" double precision,
    "motivo" text,
    "fecha" date
      );


alter table "public"."pagos" enable row level security;


  create table "public"."pagos_documentos" (
    "id" bigint generated by default as identity not null,
    "id_pago" bigint,
    "id_documento" bigint
      );


alter table "public"."pagos_documentos" enable row level security;


  create table "public"."pedidos" (
    "id" bigint generated by default as identity not null,
    "id_grupo" bigint not null,
    "talles" text,
    "envio_gratis" boolean,
    "observaciones" text,
    "estado_general" text default 'Venta realizada'::text,
    "fecha_aprobacion_boceto" date,
    "fecha_aprobacion_talles" date,
    "colores" text,
    "cantidad_hermanos" smallint default '0'::smallint,
    "porcentaje_descuento_hermanos" smallint,
    "id_vendedora" bigint,
    "estado_boceto" text,
    "estado_talles" text,
    "id_diseñadora" bigint,
    "molderias" text
      );


alter table "public"."pedidos" enable row level security;


  create table "public"."permisos" (
    "id" bigint generated by default as identity not null,
    "nombre" text,
    "descripcion" text
      );


alter table "public"."permisos" enable row level security;


  create table "public"."precios_productos" (
    "id" bigint generated by default as identity not null,
    "id_producto" bigint not null,
    "cantidad_desde" integer not null,
    "cantidad_hasta" integer not null,
    "cuotas" integer not null,
    "valor_senia" real not null,
    "valor_cuota" real not null,
    "beneficio" text
      );


alter table "public"."precios_productos" enable row level security;


  create table "public"."prendas_pedido" (
    "id" bigint generated by default as identity not null,
    "pedido" bigint not null,
    "talle" text,
    "producto" bigint,
    "inscripcion" text
      );


alter table "public"."prendas_pedido" enable row level security;


  create table "public"."productos" (
    "id" bigint generated by default as identity not null,
    "nombre" text not null,
    "descripcion" text not null
      );


alter table "public"."productos" enable row level security;


  create table "public"."productos_pedidos" (
    "id" bigint generated by default as identity not null,
    "id_pedido" bigint not null,
    "id_producto_original" bigint not null,
    "cantidad" integer not null,
    "descripcion" text,
    "valor_senia" real not null,
    "valor_cuota" real not null,
    "beneficio" text
      );


alter table "public"."productos_pedidos" enable row level security;


  create table "public"."roles" (
    "id" bigint generated by default as identity not null,
    "rol" bigint not null,
    "nombre_rol" text not null
      );


alter table "public"."roles" enable row level security;


  create table "public"."roles_permisos" (
    "id" bigint generated by default as identity not null,
    "rol_nro" bigint,
    "permiso_id" bigint
      );


alter table "public"."roles_permisos" enable row level security;


  create table "public"."usuarios" (
    "id" bigint generated by default as identity not null,
    "id_auth" uuid not null,
    "nombre" text,
    "apellido" text,
    "rol" bigint,
    "aprobado" boolean not null default false
      );


alter table "public"."usuarios" enable row level security;

CREATE UNIQUE INDEX agregados_pkey ON public.agregados USING btree (id);

CREATE UNIQUE INDEX alumnos_responsables_pkey ON public.alumnos_responsables USING btree (id);

CREATE UNIQUE INDEX auditoria_pkey ON public.auditoria USING btree (id);

CREATE UNIQUE INDEX beneficios_pkey ON public.beneficios USING btree (id);

CREATE UNIQUE INDEX colegios_pkey ON public.colegios USING btree (id);

CREATE UNIQUE INDEX combos_pkey ON public.productos USING btree (id);

CREATE UNIQUE INDEX contratos_pkey ON public.contratos USING btree (id);

CREATE UNIQUE INDEX cuotas_pkey ON public.cuotas USING btree (id);

CREATE UNIQUE INDEX documentos_pkey ON public.documentos USING btree (id);

CREATE UNIQUE INDEX grupos_pkey ON public.grupos USING btree (id);

CREATE UNIQUE INDEX grupos_unicos ON public.grupos USING btree (id_colegio, nivel, turno, orientacion, promo);

CREATE UNIQUE INDEX movimientos_pkey ON public.movimientos USING btree (id);

CREATE UNIQUE INDEX padres_responsables_pkey ON public.padres_responsables USING btree (id);

CREATE UNIQUE INDEX pagos_documentos_pkey ON public.pagos_documentos USING btree (id);

CREATE UNIQUE INDEX pagos_pkey ON public.pagos USING btree (id);

CREATE UNIQUE INDEX pedidos_pkey ON public.pedidos USING btree (id);

CREATE UNIQUE INDEX permisos_pkey ON public.permisos USING btree (id);

CREATE UNIQUE INDEX precios_productos_pkey ON public.precios_productos USING btree (id);

CREATE UNIQUE INDEX prendas_pedido_pkey ON public.prendas_pedido USING btree (id);

CREATE UNIQUE INDEX productos_pedidos_pkey ON public.productos_pedidos USING btree (id);

CREATE UNIQUE INDEX roles_permisos_pkey ON public.roles_permisos USING btree (id);

CREATE UNIQUE INDEX roles_pkey ON public.roles USING btree (nombre_rol);

CREATE UNIQUE INDEX roles_rol_key ON public.roles USING btree (rol);

CREATE UNIQUE INDEX usuarios_pkey ON public.usuarios USING btree (id);

alter table "public"."agregados" add constraint "agregados_pkey" PRIMARY KEY using index "agregados_pkey";

alter table "public"."alumnos_responsables" add constraint "alumnos_responsables_pkey" PRIMARY KEY using index "alumnos_responsables_pkey";

alter table "public"."auditoria" add constraint "auditoria_pkey" PRIMARY KEY using index "auditoria_pkey";

alter table "public"."beneficios" add constraint "beneficios_pkey" PRIMARY KEY using index "beneficios_pkey";

alter table "public"."colegios" add constraint "colegios_pkey" PRIMARY KEY using index "colegios_pkey";

alter table "public"."contratos" add constraint "contratos_pkey" PRIMARY KEY using index "contratos_pkey";

alter table "public"."cuotas" add constraint "cuotas_pkey" PRIMARY KEY using index "cuotas_pkey";

alter table "public"."documentos" add constraint "documentos_pkey" PRIMARY KEY using index "documentos_pkey";

alter table "public"."grupos" add constraint "grupos_pkey" PRIMARY KEY using index "grupos_pkey";

alter table "public"."movimientos" add constraint "movimientos_pkey" PRIMARY KEY using index "movimientos_pkey";

alter table "public"."padres_responsables" add constraint "padres_responsables_pkey" PRIMARY KEY using index "padres_responsables_pkey";

alter table "public"."pagos" add constraint "pagos_pkey" PRIMARY KEY using index "pagos_pkey";

alter table "public"."pagos_documentos" add constraint "pagos_documentos_pkey" PRIMARY KEY using index "pagos_documentos_pkey";

alter table "public"."pedidos" add constraint "pedidos_pkey" PRIMARY KEY using index "pedidos_pkey";

alter table "public"."permisos" add constraint "permisos_pkey" PRIMARY KEY using index "permisos_pkey";

alter table "public"."precios_productos" add constraint "precios_productos_pkey" PRIMARY KEY using index "precios_productos_pkey";

alter table "public"."prendas_pedido" add constraint "prendas_pedido_pkey" PRIMARY KEY using index "prendas_pedido_pkey";

alter table "public"."productos" add constraint "combos_pkey" PRIMARY KEY using index "combos_pkey";

alter table "public"."productos_pedidos" add constraint "productos_pedidos_pkey" PRIMARY KEY using index "productos_pedidos_pkey";

alter table "public"."roles" add constraint "roles_pkey" PRIMARY KEY using index "roles_pkey";

alter table "public"."roles_permisos" add constraint "roles_permisos_pkey" PRIMARY KEY using index "roles_permisos_pkey";

alter table "public"."usuarios" add constraint "usuarios_pkey" PRIMARY KEY using index "usuarios_pkey";

alter table "public"."alumnos_responsables" add constraint "alumnos_responsables_id_grupo_fkey" FOREIGN KEY (id_grupo) REFERENCES public.grupos(id) not valid;

alter table "public"."alumnos_responsables" validate constraint "alumnos_responsables_id_grupo_fkey";

alter table "public"."auditoria" add constraint "auditoria_usuario_fkey" FOREIGN KEY (usuario) REFERENCES public.usuarios(id) not valid;

alter table "public"."auditoria" validate constraint "auditoria_usuario_fkey";

alter table "public"."contratos" add constraint "contratos_documento_fkey" FOREIGN KEY (documento) REFERENCES public.documentos(id) not valid;

alter table "public"."contratos" validate constraint "contratos_documento_fkey";

alter table "public"."contratos" add constraint "contratos_grupo_fkey" FOREIGN KEY (grupo) REFERENCES public.grupos(id) not valid;

alter table "public"."contratos" validate constraint "contratos_grupo_fkey";

alter table "public"."cuotas" add constraint "cuotas_pedido_fkey" FOREIGN KEY (id_pedido) REFERENCES public.pedidos(id) not valid;

alter table "public"."cuotas" validate constraint "cuotas_pedido_fkey";

alter table "public"."documentos" add constraint "documentos_grupo_fkey" FOREIGN KEY (id_grupo) REFERENCES public.grupos(id) not valid;

alter table "public"."documentos" validate constraint "documentos_grupo_fkey";

alter table "public"."grupos" add constraint "grupos_colegio_fkey" FOREIGN KEY (id_colegio) REFERENCES public.colegios(id) not valid;

alter table "public"."grupos" validate constraint "grupos_colegio_fkey";

alter table "public"."grupos" add constraint "grupos_unicos" UNIQUE using index "grupos_unicos";

alter table "public"."movimientos" add constraint "movimientos_grupo_fkey" FOREIGN KEY (id_grupo) REFERENCES public.grupos(id) not valid;

alter table "public"."movimientos" validate constraint "movimientos_grupo_fkey";

alter table "public"."padres_responsables" add constraint "padres_responsables_id_grupo_fkey" FOREIGN KEY (id_grupo) REFERENCES public.grupos(id) not valid;

alter table "public"."padres_responsables" validate constraint "padres_responsables_id_grupo_fkey";

alter table "public"."pagos" add constraint "pagos_pedido_fkey" FOREIGN KEY (id_pedido) REFERENCES public.pedidos(id) not valid;

alter table "public"."pagos" validate constraint "pagos_pedido_fkey";

alter table "public"."pagos_documentos" add constraint "pagos_documentos_id_documento_fkey" FOREIGN KEY (id_documento) REFERENCES public.documentos(id) not valid;

alter table "public"."pagos_documentos" validate constraint "pagos_documentos_id_documento_fkey";

alter table "public"."pagos_documentos" add constraint "pagos_documentos_id_pago_fkey" FOREIGN KEY (id_pago) REFERENCES public.pagos(id) not valid;

alter table "public"."pagos_documentos" validate constraint "pagos_documentos_id_pago_fkey";

alter table "public"."pedidos" add constraint "pedidos_grupo_fkey" FOREIGN KEY (id_grupo) REFERENCES public.grupos(id) not valid;

alter table "public"."pedidos" validate constraint "pedidos_grupo_fkey";

alter table "public"."pedidos" add constraint "pedidos_id_vendedora_fkey" FOREIGN KEY (id_vendedora) REFERENCES public.usuarios(id) not valid;

alter table "public"."pedidos" validate constraint "pedidos_id_vendedora_fkey";

alter table "public"."precios_productos" add constraint "precios_productos_id_producto_fkey" FOREIGN KEY (id_producto) REFERENCES public.productos(id) not valid;

alter table "public"."precios_productos" validate constraint "precios_productos_id_producto_fkey";

alter table "public"."prendas_pedido" add constraint "prendas_pedido_pedido_fkey" FOREIGN KEY (pedido) REFERENCES public.pedidos(id) not valid;

alter table "public"."prendas_pedido" validate constraint "prendas_pedido_pedido_fkey";

alter table "public"."prendas_pedido" add constraint "prendas_pedido_producto_fkey" FOREIGN KEY (producto) REFERENCES public.productos(id) not valid;

alter table "public"."prendas_pedido" validate constraint "prendas_pedido_producto_fkey";

alter table "public"."productos_pedidos" add constraint "productos_pedidos_id_pedido_fkey" FOREIGN KEY (id_pedido) REFERENCES public.pedidos(id) not valid;

alter table "public"."productos_pedidos" validate constraint "productos_pedidos_id_pedido_fkey";

alter table "public"."productos_pedidos" add constraint "productos_pedidos_id_producto_original_fkey" FOREIGN KEY (id_producto_original) REFERENCES public.productos(id) not valid;

alter table "public"."productos_pedidos" validate constraint "productos_pedidos_id_producto_original_fkey";

alter table "public"."roles" add constraint "roles_rol_key" UNIQUE using index "roles_rol_key";

alter table "public"."roles_permisos" add constraint "roles_permisos_permiso_id_fkey" FOREIGN KEY (permiso_id) REFERENCES public.permisos(id) not valid;

alter table "public"."roles_permisos" validate constraint "roles_permisos_permiso_id_fkey";

alter table "public"."roles_permisos" add constraint "roles_permisos_rol_nro_fkey" FOREIGN KEY (rol_nro) REFERENCES public.roles(rol) not valid;

alter table "public"."roles_permisos" validate constraint "roles_permisos_rol_nro_fkey";

alter table "public"."usuarios" add constraint "usuarios_id_auth_fkey" FOREIGN KEY (id_auth) REFERENCES auth.users(id) not valid;

alter table "public"."usuarios" validate constraint "usuarios_id_auth_fkey";

alter table "public"."usuarios" add constraint "usuarios_rol_fkey" FOREIGN KEY (rol) REFERENCES public.roles(rol) not valid;

alter table "public"."usuarios" validate constraint "usuarios_rol_fkey";

grant delete on table "public"."agregados" to "anon";

grant insert on table "public"."agregados" to "anon";

grant references on table "public"."agregados" to "anon";

grant select on table "public"."agregados" to "anon";

grant trigger on table "public"."agregados" to "anon";

grant truncate on table "public"."agregados" to "anon";

grant update on table "public"."agregados" to "anon";

grant delete on table "public"."agregados" to "authenticated";

grant insert on table "public"."agregados" to "authenticated";

grant references on table "public"."agregados" to "authenticated";

grant select on table "public"."agregados" to "authenticated";

grant trigger on table "public"."agregados" to "authenticated";

grant truncate on table "public"."agregados" to "authenticated";

grant update on table "public"."agregados" to "authenticated";

grant delete on table "public"."agregados" to "service_role";

grant insert on table "public"."agregados" to "service_role";

grant references on table "public"."agregados" to "service_role";

grant select on table "public"."agregados" to "service_role";

grant trigger on table "public"."agregados" to "service_role";

grant truncate on table "public"."agregados" to "service_role";

grant update on table "public"."agregados" to "service_role";

grant delete on table "public"."alumnos_responsables" to "anon";

grant insert on table "public"."alumnos_responsables" to "anon";

grant references on table "public"."alumnos_responsables" to "anon";

grant select on table "public"."alumnos_responsables" to "anon";

grant trigger on table "public"."alumnos_responsables" to "anon";

grant truncate on table "public"."alumnos_responsables" to "anon";

grant update on table "public"."alumnos_responsables" to "anon";

grant delete on table "public"."alumnos_responsables" to "authenticated";

grant insert on table "public"."alumnos_responsables" to "authenticated";

grant references on table "public"."alumnos_responsables" to "authenticated";

grant select on table "public"."alumnos_responsables" to "authenticated";

grant trigger on table "public"."alumnos_responsables" to "authenticated";

grant truncate on table "public"."alumnos_responsables" to "authenticated";

grant update on table "public"."alumnos_responsables" to "authenticated";

grant delete on table "public"."alumnos_responsables" to "service_role";

grant insert on table "public"."alumnos_responsables" to "service_role";

grant references on table "public"."alumnos_responsables" to "service_role";

grant select on table "public"."alumnos_responsables" to "service_role";

grant trigger on table "public"."alumnos_responsables" to "service_role";

grant truncate on table "public"."alumnos_responsables" to "service_role";

grant update on table "public"."alumnos_responsables" to "service_role";

grant delete on table "public"."auditoria" to "anon";

grant insert on table "public"."auditoria" to "anon";

grant references on table "public"."auditoria" to "anon";

grant select on table "public"."auditoria" to "anon";

grant trigger on table "public"."auditoria" to "anon";

grant truncate on table "public"."auditoria" to "anon";

grant update on table "public"."auditoria" to "anon";

grant delete on table "public"."auditoria" to "authenticated";

grant insert on table "public"."auditoria" to "authenticated";

grant references on table "public"."auditoria" to "authenticated";

grant select on table "public"."auditoria" to "authenticated";

grant trigger on table "public"."auditoria" to "authenticated";

grant truncate on table "public"."auditoria" to "authenticated";

grant update on table "public"."auditoria" to "authenticated";

grant delete on table "public"."auditoria" to "service_role";

grant insert on table "public"."auditoria" to "service_role";

grant references on table "public"."auditoria" to "service_role";

grant select on table "public"."auditoria" to "service_role";

grant trigger on table "public"."auditoria" to "service_role";

grant truncate on table "public"."auditoria" to "service_role";

grant update on table "public"."auditoria" to "service_role";

grant delete on table "public"."beneficios" to "anon";

grant insert on table "public"."beneficios" to "anon";

grant references on table "public"."beneficios" to "anon";

grant select on table "public"."beneficios" to "anon";

grant trigger on table "public"."beneficios" to "anon";

grant truncate on table "public"."beneficios" to "anon";

grant update on table "public"."beneficios" to "anon";

grant delete on table "public"."beneficios" to "authenticated";

grant insert on table "public"."beneficios" to "authenticated";

grant references on table "public"."beneficios" to "authenticated";

grant select on table "public"."beneficios" to "authenticated";

grant trigger on table "public"."beneficios" to "authenticated";

grant truncate on table "public"."beneficios" to "authenticated";

grant update on table "public"."beneficios" to "authenticated";

grant delete on table "public"."beneficios" to "service_role";

grant insert on table "public"."beneficios" to "service_role";

grant references on table "public"."beneficios" to "service_role";

grant select on table "public"."beneficios" to "service_role";

grant trigger on table "public"."beneficios" to "service_role";

grant truncate on table "public"."beneficios" to "service_role";

grant update on table "public"."beneficios" to "service_role";

grant delete on table "public"."colegios" to "anon";

grant insert on table "public"."colegios" to "anon";

grant references on table "public"."colegios" to "anon";

grant select on table "public"."colegios" to "anon";

grant trigger on table "public"."colegios" to "anon";

grant truncate on table "public"."colegios" to "anon";

grant update on table "public"."colegios" to "anon";

grant delete on table "public"."colegios" to "authenticated";

grant insert on table "public"."colegios" to "authenticated";

grant references on table "public"."colegios" to "authenticated";

grant select on table "public"."colegios" to "authenticated";

grant trigger on table "public"."colegios" to "authenticated";

grant truncate on table "public"."colegios" to "authenticated";

grant update on table "public"."colegios" to "authenticated";

grant delete on table "public"."colegios" to "service_role";

grant insert on table "public"."colegios" to "service_role";

grant references on table "public"."colegios" to "service_role";

grant select on table "public"."colegios" to "service_role";

grant trigger on table "public"."colegios" to "service_role";

grant truncate on table "public"."colegios" to "service_role";

grant update on table "public"."colegios" to "service_role";

grant delete on table "public"."contratos" to "anon";

grant insert on table "public"."contratos" to "anon";

grant references on table "public"."contratos" to "anon";

grant select on table "public"."contratos" to "anon";

grant trigger on table "public"."contratos" to "anon";

grant truncate on table "public"."contratos" to "anon";

grant update on table "public"."contratos" to "anon";

grant delete on table "public"."contratos" to "authenticated";

grant insert on table "public"."contratos" to "authenticated";

grant references on table "public"."contratos" to "authenticated";

grant select on table "public"."contratos" to "authenticated";

grant trigger on table "public"."contratos" to "authenticated";

grant truncate on table "public"."contratos" to "authenticated";

grant update on table "public"."contratos" to "authenticated";

grant delete on table "public"."contratos" to "service_role";

grant insert on table "public"."contratos" to "service_role";

grant references on table "public"."contratos" to "service_role";

grant select on table "public"."contratos" to "service_role";

grant trigger on table "public"."contratos" to "service_role";

grant truncate on table "public"."contratos" to "service_role";

grant update on table "public"."contratos" to "service_role";

grant delete on table "public"."cuotas" to "anon";

grant insert on table "public"."cuotas" to "anon";

grant references on table "public"."cuotas" to "anon";

grant select on table "public"."cuotas" to "anon";

grant trigger on table "public"."cuotas" to "anon";

grant truncate on table "public"."cuotas" to "anon";

grant update on table "public"."cuotas" to "anon";

grant delete on table "public"."cuotas" to "authenticated";

grant insert on table "public"."cuotas" to "authenticated";

grant references on table "public"."cuotas" to "authenticated";

grant select on table "public"."cuotas" to "authenticated";

grant trigger on table "public"."cuotas" to "authenticated";

grant truncate on table "public"."cuotas" to "authenticated";

grant update on table "public"."cuotas" to "authenticated";

grant delete on table "public"."cuotas" to "service_role";

grant insert on table "public"."cuotas" to "service_role";

grant references on table "public"."cuotas" to "service_role";

grant select on table "public"."cuotas" to "service_role";

grant trigger on table "public"."cuotas" to "service_role";

grant truncate on table "public"."cuotas" to "service_role";

grant update on table "public"."cuotas" to "service_role";

grant delete on table "public"."documentos" to "anon";

grant insert on table "public"."documentos" to "anon";

grant references on table "public"."documentos" to "anon";

grant select on table "public"."documentos" to "anon";

grant trigger on table "public"."documentos" to "anon";

grant truncate on table "public"."documentos" to "anon";

grant update on table "public"."documentos" to "anon";

grant delete on table "public"."documentos" to "authenticated";

grant insert on table "public"."documentos" to "authenticated";

grant references on table "public"."documentos" to "authenticated";

grant select on table "public"."documentos" to "authenticated";

grant trigger on table "public"."documentos" to "authenticated";

grant truncate on table "public"."documentos" to "authenticated";

grant update on table "public"."documentos" to "authenticated";

grant delete on table "public"."documentos" to "service_role";

grant insert on table "public"."documentos" to "service_role";

grant references on table "public"."documentos" to "service_role";

grant select on table "public"."documentos" to "service_role";

grant trigger on table "public"."documentos" to "service_role";

grant truncate on table "public"."documentos" to "service_role";

grant update on table "public"."documentos" to "service_role";

grant delete on table "public"."grupos" to "anon";

grant insert on table "public"."grupos" to "anon";

grant references on table "public"."grupos" to "anon";

grant select on table "public"."grupos" to "anon";

grant trigger on table "public"."grupos" to "anon";

grant truncate on table "public"."grupos" to "anon";

grant update on table "public"."grupos" to "anon";

grant delete on table "public"."grupos" to "authenticated";

grant insert on table "public"."grupos" to "authenticated";

grant references on table "public"."grupos" to "authenticated";

grant select on table "public"."grupos" to "authenticated";

grant trigger on table "public"."grupos" to "authenticated";

grant truncate on table "public"."grupos" to "authenticated";

grant update on table "public"."grupos" to "authenticated";

grant delete on table "public"."grupos" to "service_role";

grant insert on table "public"."grupos" to "service_role";

grant references on table "public"."grupos" to "service_role";

grant select on table "public"."grupos" to "service_role";

grant trigger on table "public"."grupos" to "service_role";

grant truncate on table "public"."grupos" to "service_role";

grant update on table "public"."grupos" to "service_role";

grant delete on table "public"."movimientos" to "anon";

grant insert on table "public"."movimientos" to "anon";

grant references on table "public"."movimientos" to "anon";

grant select on table "public"."movimientos" to "anon";

grant trigger on table "public"."movimientos" to "anon";

grant truncate on table "public"."movimientos" to "anon";

grant update on table "public"."movimientos" to "anon";

grant delete on table "public"."movimientos" to "authenticated";

grant insert on table "public"."movimientos" to "authenticated";

grant references on table "public"."movimientos" to "authenticated";

grant select on table "public"."movimientos" to "authenticated";

grant trigger on table "public"."movimientos" to "authenticated";

grant truncate on table "public"."movimientos" to "authenticated";

grant update on table "public"."movimientos" to "authenticated";

grant delete on table "public"."movimientos" to "service_role";

grant insert on table "public"."movimientos" to "service_role";

grant references on table "public"."movimientos" to "service_role";

grant select on table "public"."movimientos" to "service_role";

grant trigger on table "public"."movimientos" to "service_role";

grant truncate on table "public"."movimientos" to "service_role";

grant update on table "public"."movimientos" to "service_role";

grant delete on table "public"."padres_responsables" to "anon";

grant insert on table "public"."padres_responsables" to "anon";

grant references on table "public"."padres_responsables" to "anon";

grant select on table "public"."padres_responsables" to "anon";

grant trigger on table "public"."padres_responsables" to "anon";

grant truncate on table "public"."padres_responsables" to "anon";

grant update on table "public"."padres_responsables" to "anon";

grant delete on table "public"."padres_responsables" to "authenticated";

grant insert on table "public"."padres_responsables" to "authenticated";

grant references on table "public"."padres_responsables" to "authenticated";

grant select on table "public"."padres_responsables" to "authenticated";

grant trigger on table "public"."padres_responsables" to "authenticated";

grant truncate on table "public"."padres_responsables" to "authenticated";

grant update on table "public"."padres_responsables" to "authenticated";

grant delete on table "public"."padres_responsables" to "service_role";

grant insert on table "public"."padres_responsables" to "service_role";

grant references on table "public"."padres_responsables" to "service_role";

grant select on table "public"."padres_responsables" to "service_role";

grant trigger on table "public"."padres_responsables" to "service_role";

grant truncate on table "public"."padres_responsables" to "service_role";

grant update on table "public"."padres_responsables" to "service_role";

grant delete on table "public"."pagos" to "anon";

grant insert on table "public"."pagos" to "anon";

grant references on table "public"."pagos" to "anon";

grant select on table "public"."pagos" to "anon";

grant trigger on table "public"."pagos" to "anon";

grant truncate on table "public"."pagos" to "anon";

grant update on table "public"."pagos" to "anon";

grant delete on table "public"."pagos" to "authenticated";

grant insert on table "public"."pagos" to "authenticated";

grant references on table "public"."pagos" to "authenticated";

grant select on table "public"."pagos" to "authenticated";

grant trigger on table "public"."pagos" to "authenticated";

grant truncate on table "public"."pagos" to "authenticated";

grant update on table "public"."pagos" to "authenticated";

grant delete on table "public"."pagos" to "service_role";

grant insert on table "public"."pagos" to "service_role";

grant references on table "public"."pagos" to "service_role";

grant select on table "public"."pagos" to "service_role";

grant trigger on table "public"."pagos" to "service_role";

grant truncate on table "public"."pagos" to "service_role";

grant update on table "public"."pagos" to "service_role";

grant delete on table "public"."pagos_documentos" to "anon";

grant insert on table "public"."pagos_documentos" to "anon";

grant references on table "public"."pagos_documentos" to "anon";

grant select on table "public"."pagos_documentos" to "anon";

grant trigger on table "public"."pagos_documentos" to "anon";

grant truncate on table "public"."pagos_documentos" to "anon";

grant update on table "public"."pagos_documentos" to "anon";

grant delete on table "public"."pagos_documentos" to "authenticated";

grant insert on table "public"."pagos_documentos" to "authenticated";

grant references on table "public"."pagos_documentos" to "authenticated";

grant select on table "public"."pagos_documentos" to "authenticated";

grant trigger on table "public"."pagos_documentos" to "authenticated";

grant truncate on table "public"."pagos_documentos" to "authenticated";

grant update on table "public"."pagos_documentos" to "authenticated";

grant delete on table "public"."pagos_documentos" to "service_role";

grant insert on table "public"."pagos_documentos" to "service_role";

grant references on table "public"."pagos_documentos" to "service_role";

grant select on table "public"."pagos_documentos" to "service_role";

grant trigger on table "public"."pagos_documentos" to "service_role";

grant truncate on table "public"."pagos_documentos" to "service_role";

grant update on table "public"."pagos_documentos" to "service_role";

grant delete on table "public"."pedidos" to "anon";

grant insert on table "public"."pedidos" to "anon";

grant references on table "public"."pedidos" to "anon";

grant select on table "public"."pedidos" to "anon";

grant trigger on table "public"."pedidos" to "anon";

grant truncate on table "public"."pedidos" to "anon";

grant update on table "public"."pedidos" to "anon";

grant delete on table "public"."pedidos" to "authenticated";

grant insert on table "public"."pedidos" to "authenticated";

grant references on table "public"."pedidos" to "authenticated";

grant select on table "public"."pedidos" to "authenticated";

grant trigger on table "public"."pedidos" to "authenticated";

grant truncate on table "public"."pedidos" to "authenticated";

grant update on table "public"."pedidos" to "authenticated";

grant delete on table "public"."pedidos" to "service_role";

grant insert on table "public"."pedidos" to "service_role";

grant references on table "public"."pedidos" to "service_role";

grant select on table "public"."pedidos" to "service_role";

grant trigger on table "public"."pedidos" to "service_role";

grant truncate on table "public"."pedidos" to "service_role";

grant update on table "public"."pedidos" to "service_role";

grant delete on table "public"."permisos" to "anon";

grant insert on table "public"."permisos" to "anon";

grant references on table "public"."permisos" to "anon";

grant select on table "public"."permisos" to "anon";

grant trigger on table "public"."permisos" to "anon";

grant truncate on table "public"."permisos" to "anon";

grant update on table "public"."permisos" to "anon";

grant delete on table "public"."permisos" to "authenticated";

grant insert on table "public"."permisos" to "authenticated";

grant references on table "public"."permisos" to "authenticated";

grant select on table "public"."permisos" to "authenticated";

grant trigger on table "public"."permisos" to "authenticated";

grant truncate on table "public"."permisos" to "authenticated";

grant update on table "public"."permisos" to "authenticated";

grant delete on table "public"."permisos" to "service_role";

grant insert on table "public"."permisos" to "service_role";

grant references on table "public"."permisos" to "service_role";

grant select on table "public"."permisos" to "service_role";

grant trigger on table "public"."permisos" to "service_role";

grant truncate on table "public"."permisos" to "service_role";

grant update on table "public"."permisos" to "service_role";

grant delete on table "public"."precios_productos" to "anon";

grant insert on table "public"."precios_productos" to "anon";

grant references on table "public"."precios_productos" to "anon";

grant select on table "public"."precios_productos" to "anon";

grant trigger on table "public"."precios_productos" to "anon";

grant truncate on table "public"."precios_productos" to "anon";

grant update on table "public"."precios_productos" to "anon";

grant delete on table "public"."precios_productos" to "authenticated";

grant insert on table "public"."precios_productos" to "authenticated";

grant references on table "public"."precios_productos" to "authenticated";

grant select on table "public"."precios_productos" to "authenticated";

grant trigger on table "public"."precios_productos" to "authenticated";

grant truncate on table "public"."precios_productos" to "authenticated";

grant update on table "public"."precios_productos" to "authenticated";

grant delete on table "public"."precios_productos" to "service_role";

grant insert on table "public"."precios_productos" to "service_role";

grant references on table "public"."precios_productos" to "service_role";

grant select on table "public"."precios_productos" to "service_role";

grant trigger on table "public"."precios_productos" to "service_role";

grant truncate on table "public"."precios_productos" to "service_role";

grant update on table "public"."precios_productos" to "service_role";

grant delete on table "public"."prendas_pedido" to "anon";

grant insert on table "public"."prendas_pedido" to "anon";

grant references on table "public"."prendas_pedido" to "anon";

grant select on table "public"."prendas_pedido" to "anon";

grant trigger on table "public"."prendas_pedido" to "anon";

grant truncate on table "public"."prendas_pedido" to "anon";

grant update on table "public"."prendas_pedido" to "anon";

grant delete on table "public"."prendas_pedido" to "authenticated";

grant insert on table "public"."prendas_pedido" to "authenticated";

grant references on table "public"."prendas_pedido" to "authenticated";

grant select on table "public"."prendas_pedido" to "authenticated";

grant trigger on table "public"."prendas_pedido" to "authenticated";

grant truncate on table "public"."prendas_pedido" to "authenticated";

grant update on table "public"."prendas_pedido" to "authenticated";

grant delete on table "public"."prendas_pedido" to "service_role";

grant insert on table "public"."prendas_pedido" to "service_role";

grant references on table "public"."prendas_pedido" to "service_role";

grant select on table "public"."prendas_pedido" to "service_role";

grant trigger on table "public"."prendas_pedido" to "service_role";

grant truncate on table "public"."prendas_pedido" to "service_role";

grant update on table "public"."prendas_pedido" to "service_role";

grant delete on table "public"."productos" to "anon";

grant insert on table "public"."productos" to "anon";

grant references on table "public"."productos" to "anon";

grant select on table "public"."productos" to "anon";

grant trigger on table "public"."productos" to "anon";

grant truncate on table "public"."productos" to "anon";

grant update on table "public"."productos" to "anon";

grant delete on table "public"."productos" to "authenticated";

grant insert on table "public"."productos" to "authenticated";

grant references on table "public"."productos" to "authenticated";

grant select on table "public"."productos" to "authenticated";

grant trigger on table "public"."productos" to "authenticated";

grant truncate on table "public"."productos" to "authenticated";

grant update on table "public"."productos" to "authenticated";

grant delete on table "public"."productos" to "service_role";

grant insert on table "public"."productos" to "service_role";

grant references on table "public"."productos" to "service_role";

grant select on table "public"."productos" to "service_role";

grant trigger on table "public"."productos" to "service_role";

grant truncate on table "public"."productos" to "service_role";

grant update on table "public"."productos" to "service_role";

grant delete on table "public"."productos_pedidos" to "anon";

grant insert on table "public"."productos_pedidos" to "anon";

grant references on table "public"."productos_pedidos" to "anon";

grant select on table "public"."productos_pedidos" to "anon";

grant trigger on table "public"."productos_pedidos" to "anon";

grant truncate on table "public"."productos_pedidos" to "anon";

grant update on table "public"."productos_pedidos" to "anon";

grant delete on table "public"."productos_pedidos" to "authenticated";

grant insert on table "public"."productos_pedidos" to "authenticated";

grant references on table "public"."productos_pedidos" to "authenticated";

grant select on table "public"."productos_pedidos" to "authenticated";

grant trigger on table "public"."productos_pedidos" to "authenticated";

grant truncate on table "public"."productos_pedidos" to "authenticated";

grant update on table "public"."productos_pedidos" to "authenticated";

grant delete on table "public"."productos_pedidos" to "service_role";

grant insert on table "public"."productos_pedidos" to "service_role";

grant references on table "public"."productos_pedidos" to "service_role";

grant select on table "public"."productos_pedidos" to "service_role";

grant trigger on table "public"."productos_pedidos" to "service_role";

grant truncate on table "public"."productos_pedidos" to "service_role";

grant update on table "public"."productos_pedidos" to "service_role";

grant delete on table "public"."roles" to "anon";

grant insert on table "public"."roles" to "anon";

grant references on table "public"."roles" to "anon";

grant select on table "public"."roles" to "anon";

grant trigger on table "public"."roles" to "anon";

grant truncate on table "public"."roles" to "anon";

grant update on table "public"."roles" to "anon";

grant delete on table "public"."roles" to "authenticated";

grant insert on table "public"."roles" to "authenticated";

grant references on table "public"."roles" to "authenticated";

grant select on table "public"."roles" to "authenticated";

grant trigger on table "public"."roles" to "authenticated";

grant truncate on table "public"."roles" to "authenticated";

grant update on table "public"."roles" to "authenticated";

grant delete on table "public"."roles" to "service_role";

grant insert on table "public"."roles" to "service_role";

grant references on table "public"."roles" to "service_role";

grant select on table "public"."roles" to "service_role";

grant trigger on table "public"."roles" to "service_role";

grant truncate on table "public"."roles" to "service_role";

grant update on table "public"."roles" to "service_role";

grant delete on table "public"."roles_permisos" to "anon";

grant insert on table "public"."roles_permisos" to "anon";

grant references on table "public"."roles_permisos" to "anon";

grant select on table "public"."roles_permisos" to "anon";

grant trigger on table "public"."roles_permisos" to "anon";

grant truncate on table "public"."roles_permisos" to "anon";

grant update on table "public"."roles_permisos" to "anon";

grant delete on table "public"."roles_permisos" to "authenticated";

grant insert on table "public"."roles_permisos" to "authenticated";

grant references on table "public"."roles_permisos" to "authenticated";

grant select on table "public"."roles_permisos" to "authenticated";

grant trigger on table "public"."roles_permisos" to "authenticated";

grant truncate on table "public"."roles_permisos" to "authenticated";

grant update on table "public"."roles_permisos" to "authenticated";

grant delete on table "public"."roles_permisos" to "service_role";

grant insert on table "public"."roles_permisos" to "service_role";

grant references on table "public"."roles_permisos" to "service_role";

grant select on table "public"."roles_permisos" to "service_role";

grant trigger on table "public"."roles_permisos" to "service_role";

grant truncate on table "public"."roles_permisos" to "service_role";

grant update on table "public"."roles_permisos" to "service_role";

grant delete on table "public"."usuarios" to "anon";

grant insert on table "public"."usuarios" to "anon";

grant references on table "public"."usuarios" to "anon";

grant select on table "public"."usuarios" to "anon";

grant trigger on table "public"."usuarios" to "anon";

grant truncate on table "public"."usuarios" to "anon";

grant update on table "public"."usuarios" to "anon";

grant delete on table "public"."usuarios" to "authenticated";

grant insert on table "public"."usuarios" to "authenticated";

grant references on table "public"."usuarios" to "authenticated";

grant select on table "public"."usuarios" to "authenticated";

grant trigger on table "public"."usuarios" to "authenticated";

grant truncate on table "public"."usuarios" to "authenticated";

grant update on table "public"."usuarios" to "authenticated";

grant delete on table "public"."usuarios" to "service_role";

grant insert on table "public"."usuarios" to "service_role";

grant references on table "public"."usuarios" to "service_role";

grant select on table "public"."usuarios" to "service_role";

grant trigger on table "public"."usuarios" to "service_role";

grant truncate on table "public"."usuarios" to "service_role";

grant update on table "public"."usuarios" to "service_role";


  create policy "Usuarios pueden ver su propia fila"
  on "public"."usuarios"
  as permissive
  for select
  to authenticated
using ((auth.uid() = id_auth));



