create table public.notificaciones_whatsapp (
    id bigint generated by default as identity primary key,
    id_pedido bigint not null references public.pedidos(id) on delete cascade,
    id_cuota bigint references public.cuotas(id) on delete cascade,  
    plantilla text not null,
    estado text not null default 'pendiente'
        check (estado in ('pendiente', 'enviado', 'error', 'cancelado')),
    fecha_programada date
);

alter table public.notificaciones_whatsapp enable row level security;