-- Beneficios del pedido pasan de ser un texto repetido en cada fila de
-- productos_pedidos ("2 Camperas liberadas - 1 Bandera") a una tabla propia,
-- igual que productos_pedidos / agregados_globales_pedido.
--
-- Además, un beneficio del catálogo puede apuntar a un producto (prendas
-- liberadas). Eso permite, al armar el resumen de talles y el presupuesto,
-- descontar esas prendas del producto pedido y mostrarlas como regalo.
--
-- IMPORTANTE: esta migración dropea productos_pedidos.beneficio. El backend
-- que todavía escribe esa columna (confirmar talles, modificarBeneficios)
-- tiene que actualizarse y desplegarse junto con esta migración.


-- 1) Catálogo: beneficio opcionalmente asociado a un producto --------------

alter table public.beneficios
    add column id_producto bigint null;

alter table public.beneficios
    add constraint beneficios_id_producto_fkey
    foreign key (id_producto) references public.productos(id);


-- 2) Tabla beneficios_pedido ------------------------------------------------

create table public.beneficios_pedido (
    id           bigint generated by default as identity not null,
    id_pedido    bigint not null,
    id_beneficio bigint not null,
    cantidad     integer not null default 1
);

alter table public.beneficios_pedido
    add constraint beneficios_pedido_pkey primary key (id);

alter table public.beneficios_pedido
    add constraint beneficios_pedido_id_pedido_fkey
    foreign key (id_pedido) references public.pedidos(id) on delete cascade;

-- Sin cascade: no se puede borrar del catálogo un beneficio que está en uso.
alter table public.beneficios_pedido
    add constraint beneficios_pedido_id_beneficio_fkey
    foreign key (id_beneficio) references public.beneficios(id);

alter table public.beneficios_pedido
    add constraint beneficios_pedido_cantidad_check check (cantidad > 0);

-- Un mismo beneficio aparece una sola vez por pedido (se suman cantidades).
alter table public.beneficios_pedido
    add constraint beneficios_pedido_pedido_beneficio_unique unique (id_pedido, id_beneficio);

create index idx_beneficios_pedido_id_pedido on public.beneficios_pedido using btree (id_pedido);

alter table public.beneficios_pedido enable row level security;

grant delete, insert, references, select, trigger, truncate, update
    on table public.beneficios_pedido to anon, authenticated, service_role;
grant all on sequence public.beneficios_pedido_id_seq to anon, authenticated, service_role;


-- 3) Migrar datos existentes -----------------------------------------------
-- El texto viene de textoBeneficios() del front: "N nombre - N nombre".
-- Se toma un texto por pedido (es el mismo repetido en todas sus filas).

-- Respaldo del texto viejo, por si algo no matchea con el catálogo.
-- Se puede dropear a mano una vez revisado.
create table public._backup_beneficio_texto_pedido as
select distinct on (id_pedido) id_pedido, beneficio as beneficio_texto
from public.productos_pedidos
where beneficio is not null
  and trim(beneficio) <> ''
  and lower(trim(beneficio)) <> 'sin beneficio'
order by id_pedido, id;

-- Sin RLS quedaría expuesta por la API de Supabase.
alter table public._backup_beneficio_texto_pedido enable row level security;

with partes as (
    select b.id_pedido,
           trim(parte) as parte
    from public._backup_beneficio_texto_pedido b,
         regexp_split_to_table(b.beneficio_texto, '\s+-\s+') as parte
),
parseado as (
    select id_pedido,
           coalesce((substring(parte from '^(\d+)\s+'))::int, 1)       as cantidad,
           trim(regexp_replace(parte, '^\d+\s+', ''))                   as nombre
    from partes
    where parte <> ''
)
insert into public.beneficios_pedido (id_pedido, id_beneficio, cantidad)
select p.id_pedido, ben.id, sum(p.cantidad)
from parseado p
join public.beneficios ben on lower(trim(ben.beneficio)) = lower(p.nombre)
group by p.id_pedido, ben.id;

-- Aviso de lo que no se pudo matchear (queda en el backup).
do $$
declare
    r record;
begin
    for r in
        select b.id_pedido, b.beneficio_texto
        from public._backup_beneficio_texto_pedido b
        where not exists (select 1 from public.beneficios_pedido bp where bp.id_pedido = b.id_pedido)
    loop
        raise notice 'Beneficio sin migrar - pedido %: "%"', r.id_pedido, r.beneficio_texto;
    end loop;
end $$;


-- 4) Dropear la columna vieja -----------------------------------------------

alter table public.productos_pedidos drop column beneficio;


-- 5) crear_pedido_completo: productos sin beneficio + beneficiosDTO ---------
-- Payload nuevo: "beneficiosDTO": [{ "id_beneficio": 3, "cantidad": 2 }, ...]
-- (opcional; si no viene o viene vacío, el pedido queda sin beneficios).

create or replace function public.crear_pedido_completo(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  id_colegio      bigint;
  id_grupo        bigint;
  id_pedido       bigint;
  id_pago         bigint;
  id_documento    bigint;
  producto        jsonb;
  beneficio       jsonb;
  padre           jsonb;
  alumno          jsonb;
  documento       jsonb;
  pago            jsonb;
  agregado_global jsonb;
  nro_cuotas      int;
  fecha_primera   date;
  importe_cuota   double precision;
  numero_primera  int;
  dia_original    int;
  fecha_mes_base  date;
  ultimo_dia_mes  int;
  fecha_calculada date;
  i               int;
  usuario_base    text;
  usuario_final   text;
  intento         int;
begin
  -- Colegio (con deduplicación por nombre + localidad, igual que crearColegio())
  select id into id_colegio
  from colegios
  where nombre = payload->'colegioDTO'->>'nombre'
    and localidad = payload->'colegioDTO'->>'localidad'
  limit 1;

  if id_colegio is null then
    insert into colegios (nombre, localidad, provincia)
    values (
      payload->'colegioDTO'->>'nombre',
      payload->'colegioDTO'->>'localidad',
      payload->'colegioDTO'->>'provincia'
    )
    returning id into id_colegio;
  end if;

  -- Grupo
  insert into grupos (id_colegio, orientacion, turno, nivel, promo, cantidad_egresados)
  values (
    id_colegio,
    payload->'grupoDTO'->>'orientacion',
    payload->'grupoDTO'->>'turno',
    payload->'grupoDTO'->>'nivel',
    (payload->'grupoDTO'->>'promo')::bigint,
    (payload->'grupoDTO'->>'cantidad_egresados')::bigint
  )
  returning id into id_grupo;

  -- Cliente: acceso al portal para este grupo
  usuario_base := payload->>'usuario';
  usuario_final := usuario_base;
  intento := 1;

  while exists (select 1 from clientes where usuario = usuario_final) loop
    intento := intento + 1;
    usuario_final := usuario_base || intento::text;
  end loop;

  insert into clientes (id_grupo, usuario, contrasena_hash)
  values (id_grupo, usuario_final, payload->>'contrasena_hash');

  -- Pedido
  insert into pedidos (
    id_grupo, talles, envio_gratis, observaciones, estado_general,
    fecha_aprobacion_boceto, fecha_aprobacion_talles, colores,molderias,
    cantidad_hermanos, porcentaje_descuento_hermanos, id_vendedora,
    estado_boceto, estado_talles, id_disenadora
  )
  values (
    id_grupo,
    payload->'pedidoDTO'->>'talles',
    (payload->'pedidoDTO'->>'envio_gratis')::boolean,
    payload->'pedidoDTO'->>'observaciones',
    payload->'pedidoDTO'->>'estado_general',
    (payload->'pedidoDTO'->>'fecha_aprobacion_boceto')::date,
    (payload->'pedidoDTO'->>'fecha_aprobacion_talles')::date,
    payload->'pedidoDTO'->>'colores',
    payload->'pedidoDTO'->>'molderias',
    coalesce((payload->'pedidoDTO'->>'cantidad_hermanos')::smallint, 0),
    (payload->'pedidoDTO'->>'porcentaje_descuento_hermanos')::smallint,
    (payload->'pedidoDTO'->>'id_vendedora')::bigint,
    payload->'pedidoDTO'->>'estado_boceto',
    payload->'pedidoDTO'->>'estado_talles',
    (payload->'pedidoDTO'->>'id_disenadora')::bigint
  )
  returning id into id_pedido;

  -- Productos del pedido
  for producto in select * from jsonb_array_elements(payload->'productosPedidoDTO')
  loop
    insert into productos_pedidos (
      id_pedido, id_producto_original, cantidad, descripcion, valor_senia, valor_cuota
    )
    values (
      id_pedido,
      (producto->>'id_producto_original')::bigint,
      (producto->>'cantidad')::int,
      producto->>'descripcion',
      (producto->>'valor_senia')::real,
      (producto->>'valor_cuota')::real
    );
  end loop;

  -- Beneficios del pedido (elegidos del catálogo por la vendedora)
  for beneficio in select * from jsonb_array_elements(coalesce(payload->'beneficiosDTO', '[]'::jsonb))
  loop
    insert into beneficios_pedido (id_pedido, id_beneficio, cantidad)
    values (
      id_pedido,
      (beneficio->>'id_beneficio')::bigint,
      coalesce((beneficio->>'cantidad')::int, 1)
    );
  end loop;

  -- Agregados globales del pedido (ej. bandera)
  for agregado_global in select * from jsonb_array_elements(coalesce(payload->'agregadosGlobalesDTO', '[]'::jsonb))
  loop
    insert into agregados_globales_pedido (id_pedido, id_agregado)
    values (id_pedido, (agregado_global->>'id_agregado')::bigint);
  end loop;

  -- Padres responsables
  for padre in select * from jsonb_array_elements(payload->'padresResponsablesDTO')
  loop
    insert into padres_responsables (nombre, apellido, dni, telefono, mail, id_grupo)
    values (
      padre->>'nombre',
      padre->>'apellido',
      padre->>'dni',
      padre->>'telefono',
      padre->>'mail',
      id_grupo
    );
  end loop;

  -- Alumnos responsables
  for alumno in select * from jsonb_array_elements(payload->'alumnosResponsablesDTO')
  loop
    insert into alumnos_responsables (id_grupo, nombre, apellido, telefono)
    values (
      id_grupo,
      alumno->>'nombre',
      alumno->>'apellido',
      alumno->>'telefono'
    );
  end loop;

  -- Pagos, cada uno con su propio comprobante (1 a 1)
  FOR pago IN SELECT * FROM jsonb_array_elements(payload->'pagosDTO')
  LOOP
    id_documento := null;

    IF pago->'documentoDTO' IS NOT NULL AND jsonb_typeof(pago->'documentoDTO') <> 'null' THEN
      INSERT INTO documentos (id_grupo, tipo, archivo_url)
      VALUES (
        id_grupo,
        pago->'documentoDTO'->>'tipo',
        pago->'documentoDTO'->>'archivo_url'
      )
      RETURNING id INTO id_documento;
    END IF;

    INSERT INTO pagos (id_pedido, id_documento, nro_transferencia, monto, motivo, fecha, aprobado, banco, entidad_pago)
    VALUES (
      id_pedido,
      id_documento,
      pago->>'nro_transferencia',
      (pago->>'monto')::double precision,
      pago->>'motivo',
      (pago->>'fecha')::date,
      (pago->>'aprobado')::boolean,
      pago->>'banco',
      pago->>'entidad_pago'
    )
    RETURNING id INTO id_pago;
  END LOOP;

  -- Documentos que no son comprobante de ningún pago (ej: recursos adicionales)
  IF payload->'documentoDTO' IS NOT NULL AND jsonb_typeof(payload->'documentoDTO') <> 'null' THEN
    if jsonb_typeof(payload->'documentoDTO') = 'array' then
      for documento in select * from jsonb_array_elements(payload->'documentoDTO')
      loop
        insert into documentos (id_grupo, tipo, archivo_url)
        values (id_grupo, documento->>'tipo', documento->>'archivo_url');
      end loop;
    else
      insert into documentos (id_grupo, tipo, archivo_url)
      values (
        id_grupo,
        payload->'documentoDTO'->>'tipo',
        payload->'documentoDTO'->>'archivo_url'
      );
    end if;
  END IF;

  -- Cuotas: primera viene en 'primerCuota', el resto se calculan
  -- replicando CuotasService.acomodarFecha().
  nro_cuotas     := (payload->>'nroCuotas')::int;
  fecha_primera  := (payload->'primerCuota'->>'fecha_vencimiento')::date;
  importe_cuota  := (payload->'primerCuota'->>'importe')::double precision;
  numero_primera := coalesce((payload->'primerCuota'->>'numero')::int, 1);
  dia_original   := extract(day from fecha_primera);

  insert into cuotas (id_pedido, numero, fecha_vencimiento, importe, estado)
  values (id_pedido, numero_primera, fecha_primera, importe_cuota, 'Pendiente');

  for i in 1..(nro_cuotas - 1) loop
    fecha_mes_base := (date_trunc('month', fecha_primera) + (i || ' months')::interval)::date;
    ultimo_dia_mes := extract(day from (fecha_mes_base + interval '1 month - 1 day'));
    fecha_calculada := fecha_mes_base + (least(dia_original, ultimo_dia_mes) - 1);

    insert into cuotas (id_pedido, numero, fecha_vencimiento, importe, estado)
    values (id_pedido, numero_primera + i, fecha_calculada, importe_cuota, 'Pendiente');
  end loop;

  return jsonb_build_object('id_pedido', id_pedido, 'usuario', usuario_final);
end;
$$;


-- 6) Reemplazar los beneficios de un pedido (edición) en una sola transacción
-- p_beneficios: [{ "id_beneficio": 3, "cantidad": 2 }, ...]  ([] = sin beneficios)

create or replace function public.modificar_beneficios_pedido(p_id_pedido bigint, p_beneficios jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from beneficios_pedido where id_pedido = p_id_pedido;

  insert into beneficios_pedido (id_pedido, id_beneficio, cantidad)
  select p_id_pedido,
         (b->>'id_beneficio')::bigint,
         sum(coalesce((b->>'cantidad')::int, 1))
  from jsonb_array_elements(coalesce(p_beneficios, '[]'::jsonb)) as b
  group by (b->>'id_beneficio')::bigint;
end;
$$;

grant all on function public.modificar_beneficios_pedido(bigint, jsonb) to anon, authenticated, service_role;
