create table "public"."muestras_fisicas" (
    "id" bigint generated by default as identity not null primary key,
    "id_pedido" bigint not null references pedidos(id),
    "estado" text,
    "muestras" text,
    "fecha_entrega" timestamptz,
    "fecha_devolucion" timestamptz
);
