create table "public"."clientes" (
    "id" bigint generated by default as identity not null,
    "id_grupo" bigint not null,
    "usuario" text not null,
    "contrasena_hash" text not null,
    "created_at" timestamp without time zone default now() not null
);

alter table "public"."clientes" enable row level security;

alter table "public"."clientes"
    add constraint "clientes_pkey" primary key ("id");

alter table "public"."clientes"
    add constraint "clientes_usuario_key" unique ("usuario");

alter table "public"."clientes"
    add constraint "clientes_id_grupo_key" unique ("id_grupo");

alter table "public"."clientes"
    add constraint "clientes_id_grupo_fkey"
    foreign key (id_grupo) references public.grupos(id);

grant delete, insert, references, select, trigger, truncate, update
    on table "public"."clientes" to "service_role";
