revoke delete on table "public"."movimientos" from "anon";

revoke insert on table "public"."movimientos" from "anon";

revoke references on table "public"."movimientos" from "anon";

revoke select on table "public"."movimientos" from "anon";

revoke trigger on table "public"."movimientos" from "anon";

revoke truncate on table "public"."movimientos" from "anon";

revoke update on table "public"."movimientos" from "anon";

revoke delete on table "public"."movimientos" from "authenticated";

revoke insert on table "public"."movimientos" from "authenticated";

revoke references on table "public"."movimientos" from "authenticated";

revoke select on table "public"."movimientos" from "authenticated";

revoke trigger on table "public"."movimientos" from "authenticated";

revoke truncate on table "public"."movimientos" from "authenticated";

revoke update on table "public"."movimientos" from "authenticated";

revoke delete on table "public"."movimientos" from "service_role";

revoke insert on table "public"."movimientos" from "service_role";

revoke references on table "public"."movimientos" from "service_role";

revoke select on table "public"."movimientos" from "service_role";

revoke trigger on table "public"."movimientos" from "service_role";

revoke truncate on table "public"."movimientos" from "service_role";

revoke update on table "public"."movimientos" from "service_role";

alter table "public"."movimientos" drop constraint "movimientos_grupo_fkey";

alter table "public"."movimientos" drop constraint "movimientos_pkey";

drop index if exists "public"."idx_movimientos_id_grupo";

drop index if exists "public"."movimientos_pkey";

drop table "public"."movimientos";


  create table "public"."movimientos_caja" (
    "id" bigint generated by default as identity not null,
    "fecha" date not null,
    "monto" numeric,
    "categoria" text,
    "descripcion" text,
    "usuario" bigint,
    "tipo" text
      );


alter table "public"."movimientos_caja" enable row level security;

CREATE UNIQUE INDEX movimientos_caja_pkey ON public.movimientos_caja USING btree (id);

alter table "public"."movimientos_caja" add constraint "movimientos_caja_pkey" PRIMARY KEY using index "movimientos_caja_pkey";

alter table "public"."movimientos_caja" add constraint "movimientos_caja_usuario_fkey" FOREIGN KEY (usuario) REFERENCES public.usuarios(id) not valid;

alter table "public"."movimientos_caja" validate constraint "movimientos_caja_usuario_fkey";

grant delete on table "public"."movimientos_caja" to "anon";

grant insert on table "public"."movimientos_caja" to "anon";

grant references on table "public"."movimientos_caja" to "anon";

grant select on table "public"."movimientos_caja" to "anon";

grant trigger on table "public"."movimientos_caja" to "anon";

grant truncate on table "public"."movimientos_caja" to "anon";

grant update on table "public"."movimientos_caja" to "anon";

grant delete on table "public"."movimientos_caja" to "authenticated";

grant insert on table "public"."movimientos_caja" to "authenticated";

grant references on table "public"."movimientos_caja" to "authenticated";

grant select on table "public"."movimientos_caja" to "authenticated";

grant trigger on table "public"."movimientos_caja" to "authenticated";

grant truncate on table "public"."movimientos_caja" to "authenticated";

grant update on table "public"."movimientos_caja" to "authenticated";

grant delete on table "public"."movimientos_caja" to "service_role";

grant insert on table "public"."movimientos_caja" to "service_role";

grant references on table "public"."movimientos_caja" to "service_role";

grant select on table "public"."movimientos_caja" to "service_role";

grant trigger on table "public"."movimientos_caja" to "service_role";

grant truncate on table "public"."movimientos_caja" to "service_role";

grant update on table "public"."movimientos_caja" to "service_role";


